version: "3.7"
services:
  app:
    build:
      args:
        user: roberth
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: learning
    container_name: learning-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - learning
  db:
    image: mysql:5.7
    container_name: learning-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: learning
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: roberth-pwd
      MYSQL_USER: roberth-usr
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - learning
  nginx:
    image: nginx:1.17-alpine
    container_name: learning-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - learning
networks:
  learning:
    driver: bridge
